"""End-to-end smoke test: seeds the demo tenant into in-memory SQLite, then drives the
real FastAPI app through httpx to confirm the whole stack -- auth, gate,
analysis, recommendations, exports -- works together, not just in isolation."""
import pytest
from httpx import ASGITransport, AsyncClient

from app.main import app
from app.seed.snakes_and_lattes import DEMO_TENANT_TOKEN, PERIOD_END, PERIOD_START, seed


@pytest.mark.asyncio
async def test_full_api_flow(db):
    seed_result = await seed(db)
    chicago_id = seed_result["location_ids"]["CHI"]
    headers = {"Authorization": f"Bearer {DEMO_TENANT_TOKEN}"}
    params = {"period_start": PERIOD_START.isoformat(), "period_end": PERIOD_END.isoformat()}

    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        # No auth -> 401
        resp = await client.get("/api/locations")
        assert resp.status_code == 401

        # Locations list
        resp = await client.get("/api/locations", headers=headers)
        assert resp.status_code == 200
        assert len(resp.json()) == 3

        # Item analysis table for Chicago
        resp = await client.get("/api/items", headers=headers, params={"location_id": chicago_id, **params})
        assert resp.status_code == 200
        items = resp.json()
        assert len(items) > 0
        assert any(i["is_food_cost_mirage"] for i in items)

        # Pareto
        resp = await client.get(
            "/api/items/pareto", headers=headers, params={"location_id": chicago_id, "metric": "revenue", **params}
        )
        assert resp.status_code == 200
        assert resp.json()["metric"] == "revenue"

        # Brand dashboard
        resp = await client.get("/api/dashboard/brand", headers=headers, params=params)
        assert resp.status_code == 200
        brand = resp.json()
        assert brand["combined_revenue"] > 0
        assert len(brand["locations"]) == 3

        # Location dashboard
        resp = await client.get(f"/api/dashboard/location/{chicago_id}", headers=headers, params=params)
        assert resp.status_code == 200
        assert resp.json()["items_analyzed"] > 0

        # Recommendations already pre-generated by seed; approve one
        resp = await client.get("/api/recommendations", headers=headers, params={"location_id": chicago_id})
        assert resp.status_code == 200
        recs = resp.json()
        assert len(recs) > 0
        price_rec = next(r for r in recs if r["type"] == "price")

        # _id isn't in the public projection -- fetch it from the raw collection instead
        raw_rec = await db.recommendations.find_one({"tenant_id": seed_result["tenant_id"], "plu": price_rec["plu"], "location_id": chicago_id})
        resp = await client.post(
            f"/api/recommendations/{raw_rec['_id']}/decide",
            headers=headers,
            json={"status": "approved", "decided_by": "test-operator"},
        )
        assert resp.status_code == 200
        assert resp.json()["status"] == "approved"

        # Pro forma reflects the approval
        resp = await client.get("/api/recommendations/pro-forma", headers=headers)
        assert resp.status_code == 200
        pro_forma = resp.json()
        assert pro_forma["queue_progress"]["approved"] >= 1

        # XLSX exports return real spreadsheet bytes
        resp = await client.get("/api/items/export.xlsx", headers=headers, params={"location_id": chicago_id, **params})
        assert resp.status_code == 200
        assert resp.headers["content-type"].startswith("application/vnd.openxmlformats")

        resp = await client.get("/api/recommendations/export-checklist.xlsx", headers=headers)
        assert resp.status_code == 200
